name: Validar Construcción de Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    name: Compilar Imagen de Docker
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Descargar código
        uses: actions/checkout@v4

      # 2. Configurar el entorno de Docker en la máquina virtual de GitHub
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Construir la imagen (sin subirla a ningún lado aún, solo para probar)
      - name: Construir Imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false # Cambia a true cuando configures un registro como Docker Hub
          tags: mi-sitio-hugo:latest